/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    TV: THREE.Mesh
    TVSCREEN: THREE.Mesh
    TVSCREENBEZEL: THREE.Mesh
  }
  materials: {
    ['TV_Chayka-206']: THREE.MeshStandardMaterial
  }
}

export function Model( props: JSX.IntrinsicElements['group'] ) {

	const { nodes, materials } = useGLTF( '/vintageTelevision.glb' ) as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.TV.geometry} material={materials[ 'TV_Chayka-206' ]} position={[ - 0.0011, 0.0054, - 0.0071 ]} scale={5.0041} />
			<mesh geometry={nodes.TVSCREEN.geometry} material={materials[ 'TV_Chayka-206' ]} position={[ - 0.0011, 0.0054, - 0.0071 ]} scale={5.0809} />
			<mesh geometry={nodes.TVSCREENBEZEL.geometry} material={materials[ 'TV_Chayka-206' ]} position={[ - 0.4388, 1.2966, 0.8396 ]} scale={[ 5.1008, 5.1032, 4.9647 ]} />
		</group>
	);

}

useGLTF.preload( '/vintageTelevision.glb' );
